# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  dev:
    desc: Runs the dev servers
    deps:
      - dev:server
      - dev:ui
    silent: true

  dev:server:
    desc: Runs the Go API server
    cmds:
      - go run cmd/server/main.go
    silent: true

  dev:ui:
    desc: Runs the Vite dev server
    dir: ui
    cmds:
      - npm run dev
    silent: true

  format:check:ui:
    desc: Checks the formatting of the UI code
    dir: ui
    cmds:
      - npm run format:check
    silent: true

  format:server:
    desc: Formats Go code with goimports
    cmds:
      - go tool goimports -w .
    silent: true

  format:ui:
    desc: Formats the UI code
    dir: ui
    cmds:
      - npm run format
    silent: true

  hooks:install:
    desc: Installs git hooks via lefthook
    cmds:
      - lefthook install

  lint:server:
    desc: Lints the Go code
    cmds:
      - golangci-lint run ./...
    silent: true

  lint:ui:
    desc: Lints the UI code
    dir: ui
    cmds:
      - npm run lint
    silent: true

  seed:
    desc: Seeds the database with development data
    cmds:
      - go run internal/cmd/seed/main.go
    silent: true

  test:server:
    desc: Runs the Go tests
    cmds:
      - go test ./...
    silent: true

  test:server:update-snapshots:
    desc: Regenerates snapshot golden files for Go tests
    cmds:
      - UPDATE_SNAPSHOTS=true go test ./...
    silent: true

  test:ui:
    desc: Runs the UI tests
    dir: ui
    cmds:
      - npm run test
    silent: true
