name: CI (UI)

on:
  pull_request:
    paths:
      - "ui/**/*.ts"
      - "ui/**/*.tsx"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - uses: arduino/setup-task@v2

      - name: Install
        run: npm ci
        working-directory: ui

      - name: Lint
        run: task lint:ui

      - name: Test
        run: task test:ui
